### ISSUE TITLE
Wheels incompatible

### ISSUE THREAD

**Issue by fredRos** [pypmc/pypmc#66]
I installed the wheel from pypi for python3.7 in conda and it didn't work

```
(inpred) [~] pip install pypmc                                                                           20:32:31 
Collecting pypmc
  Downloading https://files.pythonhosted.org/packages/15/cd/4a7c682109264357813e58c1dd478bb0f6a14085133639ecef720bd3b6d9/pypmc-1.1.4-cp37-cp37m-manylinux1_x86_64.whl (3.0MB)
    100% |████████████████████████████████| 3.0MB 1.7MB/s 
Requirement already satisfied: numpy<2.0,>=1.6 in ./.local/miniconda2/envs/inpred/lib/python3.7/site-packages (from pypmc) (1.15.4)
Collecting scipy (from pypmc)
  Using cached https://files.pythonhosted.org/packages/5d/bd/c0feba81fb60e231cf40fc8a322ed5873c90ef7711795508692b1481a4ae/scipy-1.3.0-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: scipy, pypmc
Successfully installed pypmc-1.1.4 scipy-1.3.0
(inpred) [~] python                                                                                      20:32:45 
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypmc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/beaujefr/.local/miniconda2/envs/inpred/lib/python3.7/site-packages/pypmc/__init__.py", line 9, in <module>
    from . import mix_adapt, density, sampler, tools
  File "/home/beaujefr/.local/miniconda2/envs/inpred/lib/python3.7/site-packages/pypmc/mix_adapt/__init__.py", line 7, in <module>
    from . import hierarchical, variational, pmc, r_value
  File "__init__.pxd", line 918, in init pypmc.mix_adapt.variational
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

One workaround should be to download and build from source with 

    pip install pypmc --no-binary :all:

but make sure that cython is available

**Comment by DavidMStraub** [comment]
I had the same problem in my travis builds after you released 1.1.4, and I fixed it by upgrading `numpy` to `>=1.16.2` on travis before installing `pypmc`.

**Comment by fredRos** [comment]
you mean the numpy used by the wheel builder was perhaps too old? I will check

**Comment by dvandyk** [comment]
Should be resolved now, since we are building against the stable numpy 2.0 API as of release 1.2.4.
