### ISSUE TITLE
Issue with setuptools

### ISSUE THREAD

**Issue by fredRos** [pypmc/pypmc#71]
The `ez_setup` is not ez anymore. It was a backward compatibility years ago and can probably be removed. On a pristine system with ubuntu 20.04 the recommended way to build from source fails:

```
python3 setup.py install --user
Extracting in /tmp/tmptbgmihg4
Traceback (most recent call last):
  File "/home/fred/workspace/pypmc/ez_setup.py", line 142, in use_setuptools
    pkg_resources.require("setuptools>=" + version)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'setuptools>=3.3' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    use_setuptools()
  File "/home/fred/workspace/pypmc/ez_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/fred/workspace/pypmc/ez_setup.py", line 120, in _do_download
    _build_egg(egg, archive, to_dir)
  File "/home/fred/workspace/pypmc/ez_setup.py", line 62, in _build_egg
    with archive_context(archive_filename):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/fred/workspace/pypmc/ez_setup.py", line 100, in archive_context
    with ContextualZipFile(filename) as archive:
  File "/home/fred/workspace/pypmc/ez_setup.py", line 88, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

```

## workaround

install setuptools directly 

    sudo apt install python3-setuptools

**Comment by fredRos** [comment]
Alternatively I consider dropping all support for python2...

**Comment by dvandyk** [comment]
```python
from __future__ import print_function

# bootstrap: download setuptools 3.3 if needed
from ez_setup import use_setuptools
use_setuptools()
```
removed as of 111eeac. 

I think this is fixed.
