### ISSUE TITLE
Check documentation

### ISSUE THREAD

**Issue by dvandyk** [pypmc/pypmc#84]
Fred wants to re-read the documentation and improve it where needed prior to the v1.2 release.

**Comment by fredRos** [comment]
While testing in conda with python 3.8 and building the docs, I encountered:

```
reading sources... [100%] user_guide                                                                             
/home/fred/workspace/pypmc/doc/examples.rst:23: WARNING: Exception occurred in plotting pmc_mpi
 from /home/fred/workspace/pypmc/doc/../examples/pmc_mpi.py:
Traceback (most recent call last):
  File "/home/fred/miniconda3/envs/pypmc3.8/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 472, in run_code
    exec(code, ns)
  File "<string>", line 92, in <module>
  File "/home/fred/workspace/pypmc/pypmc/tools/parallel_sampler.py", line 58, in run
    individual_return = self.sampler.run(N, *args, **kwargs)
  File "/home/fred/workspace/pypmc/pypmc/sampler/importance_sampling.py", line 190, in run
    this_samples, origin = self._get_samples(N, trace_sort=True)
  File "/home/fred/workspace/pypmc/pypmc/sampler/importance_sampling.py", line 228, in _get_samples
    this_run[:], origin = self.proposal.propose(N, self.rng, trace=True, shuffle=False)
  File "pypmc/density/mixture.pyx", line 192, in pypmc.density.mixture.MixtureDensity.propose
  File "mtrand.pyx", line 4216, in numpy.random.mtrand.RandomState.multinomial
  File "_common.pyx", line 338, in numpy.random._common.check_array_constraint
ValueError: pvals < 0, pvals > 1 or pvals contains NaNs
```

**Comment by fredRos** [comment]
I reran it, I guess it's a flaky test because we don't fix the RNG seed, no blocker
