### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by fredRos** [pypmc/pypmc#90]
see https://github.com/eos/eos/issues/411 for error messages.

After closing the issue, the same error cropped up again even though I didn't reinstall pypmc:

```console
at 21:42:27 ❯ python3.8 -c "import pypmc"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fred/.local/lib/python3.8/site-packages/pypmc/__init__.py", line 9, in <module>
    from . import mix_adapt, density, sampler, tools
  File "/home/fred/.local/lib/python3.8/site-packages/pypmc/mix_adapt/__init__.py", line 7, in <module>
    from . import hierarchical, variational, pmc, r_value
  File "pypmc/mix_adapt/variational.pyx", line 1, in init pypmc.mix_adapt.variational
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by fredRos** [comment]
The error may come from the fact that numpy was picked up from the ubuntu repos and other python modules may come with a different version? It should go away in a venv with all dependencies compatible

**Comment by dvandyk** [comment]
Closing as outdated, given that we now build wheels against the stable numpy API.
